language: ruby
rvm:
  - 2.4.2

# Use caching
cache:
  bundler: true

# Use PostgreSQL as database
services:
  - postgresql

before_script:
  - psql -c 'create database upshift_test;' -U postgres

script:
  - bundle exec rspec spec/

bundler_args: --without development production

# whitelist
branches:
  only:
    - master
    - development

# environment variables
env:
  global:
    - CI=true
    - GOOGLE_DRIVE_TRACKING_ACCOUNT=example.one@gmail.com
    - GOOGLE_DRIVE_USER_ACCOUNT=example.two@gmail.com
    - GOOGLE_DRIVE_CLIENT_ID=client_id
    - GOOGLE_DRIVE_CLIENT_SECRET=client_secret
    - GOOGLE_DRIVE_CREDENTIALS_PATH='spec/support/fixtures/google_drive/credentials.yml'
