# The location for storing Paperclip attachments, such as profile pictures
attachment_storage: 'public/system'
# Allow users to register new accounts
enable_account_registration: true
# The location for storing files, such as Git repositories
file_storage: 'system'
# The location for storing lock files
lock_storage: 'tmp/locks'
# The account used to access, monitor, and manage files
google_drive_tracking_account: <%= ENV['GOOGLE_DRIVE_TRACKING_ACCOUNT'] || 'track@flov.com' %>
# The classes whitelisted for use in YAML.safe_load
# Example: YAML.safe_load(string, Settings.whitelisted_yaml_classes)
# Read more: http://www.rubydoc.info/stdlib/psych/Psych.safe_load
whitelisted_yaml_classes: [Time]
